apiVersion: v1
name: pytorch
version: 1.3.0
appVersion: 1.3.1
description: Deep learning platform that accelerates the transition from research prototyping to production deployment
keywords:
  - pytorch
  - python
  - machine
  - learning
home: http://pytorch.org/

