{{- if .Values.backup.enabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "zeppelin-fullname" . }}-backup
  labels:
    "app.kubernetes.io/name": '{{ template "zeppelin-fullname" .}}'
    "helm.sh/chart": "{{ .Chart.Name }}-{{ .Chart.Version }}"
    "app.kubernetes.io/managed-by": "{{ .Release.Service }}"
    "app.kubernetes.io/instance": "{{ .Release.Name }}"
    "app.kubernetes.io/component": "{{ .Values.backup.componentName }}"
spec:
  schedule: {{ .Values.backup.schedule | quote }}
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 120
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            {{ toYaml .Values.backup.annotations }}
        spec:
          restartPolicy: OnFailure
          serviceAccountName: {{ template "zeppelin-fullname" . }}-backup
          containers:
          - name: zeppelin-backup
            image: "{{ .Values.backup.image.repository }}:{{ .Values.backup.image.tag }}"
            command: ["kube-tasks"]
            args:
            - simple-backup
            - -n
            - -l
            - app.kubernetes.io/instance={{ .Release.Name }}
            - --container
            - zeppelin
            - --path
            - /var/zeppelin_home
            - --dst
            - {{ .Values.backup.destination }}
            {{- with .Values.backup.extraArgs }}
{{ toYaml . | indent 12 }}
            {{- end }}
            {{- with .Values.backup.env }}
            env:
{{ toYaml . | indent 12 }}
            {{- end }}
            {{- if .Values.backup.existingSecret }}
            {{- range $key,$value := .Values.backup.existingSecret }}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ $key }}
                  key: {{ $value.awsaccesskey | quote }}
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ $key }}
                  key: {{ $value.awssecretkey | quote}}
            {{- end }}
            {{- end }}
          {{- with .Values.backup.resources }}
            resources:
{{ toYaml . | indent 14 }}
          {{- end }}
          affinity:
            podAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  topologyKey: "kubernetes.io/hostname"
                  labelSelector:
                    matchExpressions:
                    - key: app
                      operator: In
                      values:
                      - {{ template "zeppelin-fullname" . }}
                    - key: release
                      operator: In
                      values:
                      - {{ .Release.Name }}
      {{- with .Values.tolerations }}
        tolerations:
{{ toYaml . | indent 10 }}
      {{- end }}
{{- end }}
