apiVersion: v1
name: grafana
version: 3.8.14
appVersion: 6.5.1
kubeVersion: "^1.8.0-0"
description: The leading tool for querying and visualizing time series and metrics.
home: https://grafana.net
icon: https://raw.githubusercontent.com/grafana/grafana/master/public/img/logo_transparent_400x.png
maintainers:
  - name: Yobitel Communications
    email: yobitelcommunications@gmail.com
engine: gotpl
